[features]
seeds = false
skip-lint = false
[programs.localnet]
d_app = "BZSLpE8MbaY4PZZD62bwqs1PKENspL4rEnYkhg1qP4uL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/nino/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
